# Generated by Django 4.1.3 on 2022-12-08 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_retailerprofile_customerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailerprofile',
            name='website_url',
            field=models.URLField(default='Unvaible URL', max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('RETAILER', 'Retailer')], max_length=50),
        ),
    ]
