# Generated by Django 4.1.3 on 2022-12-08 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_retailerprofile_website_url_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailerprofile',
            name='retailer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.retailer'),
        ),
    ]
