# Generated by Django 4.1.3 on 2022-12-08 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_retailerprofile_retailer'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailerprofile',
            name='retailer_name',
            field=models.CharField(default='Enter Retailer Name', max_length=50),
        ),
    ]
