# Generated by Django 4.1.3 on 2022-12-08 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0007_retailerprofile_retailer_name'),
        ('main', '0002_delete_laptop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=30)),
                ('model_name', models.CharField(max_length=30)),
                ('laptop_image', models.ImageField(default='default-laptop.jpg', upload_to='laptops_pics')),
                ('price', models.CharField(max_length=30)),
                ('specs', models.TextField(max_length=500)),
                ('laptop_url', models.URLField(default='UNAVAIABLE URL', max_length=1000)),
                ('likes', models.IntegerField()),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.retailerprofile')),
            ],
        ),
    ]
