# Generated by Django 4.1.3 on 2022-12-29 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_laptop_qr_code_alter_laptop_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
