# Generated by Django 4.1.3 on 2023-01-02 11:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_laptop_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
