# Generated by Django 4.1.3 on 2023-01-02 12:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_laptop_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laptop',
            name='id',
        ),
        migrations.AlterField(
            model_name='laptop',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
