# Generated by Django 4.1.3 on 2023-01-04 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_laptop_id_alter_laptop_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='specs',
            field=models.TextField(max_length=1500),
        ),
    ]
